version: "3.7"

services:
  
  server:
    build: "./config"
    container_name: "server"
    restart: "always"
    expose:
      - "8000"

    volumes:
      - type: "bind"
        source: "./config"
        target: "/app"

    command: >
      bash -c "
        python3 manage.py migrate --noinput && \
        python3 manage.py createsuperuser --noinput; \
        gunicorn -b 0.0.0.0:8000 config.wsgi --log-level debug --reload
      "
    
    env_file:
      - .env


  nginx:
    build: "./nginx"
    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
