# Generated by Django 4.2.1 on 2023-05-13 12:27

import django.contrib.auth.models
from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_editeduser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='editeduser',
            managers=[
                ('methods', users.managers.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
