# Generated by Django 4.1.2 on 2022-12-07 21:27

import authentication.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='editeduser',
            managers=[
                ('objects', authentication.managers.EditedUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
