# Generated by Django 4.1.2 on 2022-12-07 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='name')),
                ('code', models.TextField(blank=True, null=True, verbose_name='code')),
                ('result', models.TextField(blank=True, null=True, verbose_name='result')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
