# Generated by Django 4.1.2 on 2022-12-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
